feat: cdw-31-create-endpoint-to-add-users-to-database
jtabba/CDW-1 pull request #12
Opened 2023-08-25 01:07 UTC by ifasama

as the title said and a verification to check whether username exists.

2023-08-27 05:02 UTC, jtabba requested changes
Minor changes requested - great job overall!

2023-08-27 05:02 UTC, jtabba commented on backend/src/api/v1/mentorShip/controllers/userController.ts
> +} */
Remove commented code

2023-08-27 05:02 UTC, jtabba commented on backend/src/database/userDatabase.ts
> +/* import { connectToDb } from "./db"
Unrequired comments

2023-08-30 07:20 UTC, ifasama commented
I made the changes

2023-08-30 08:35 UTC, jtabba approved these changes

2023-08-30 08:35 UTC, merged