Auth0 protected routes
jtabba/CDW-1 pull request #19
Opened 2023-08-29 01:22 UTC by noah-milliken

CDW-30 Feat added Authentication guard to Routes with login and logout buttons redirecting user to Auth0 login/sign up page.

2023-08-29 02:17 UTC, Cililocwee submitted a review, later dismissed
Hey Noah, did you mean to take out the Router wrapper in App.tsx? And make sure you merge into your branch and take care of the conflicts!

2023-08-29 02:37 UTC, jtabba requested changes
Great implementation overall Noah. Left some comments and am curious to hear why things that are not theme related are being move into `/theme`?

2023-08-29 02:37 UTC, jtabba commented on frontend/src/App.tsx
> +import { userData } from "./theme/requests/types";
Why were these moved?

2023-08-29 02:37 UTC, jtabba commented on frontend/src/App.tsx
> +			</div>
Use Chakra for UI (i.e. `Box` would be suitable here). Read the Charka docs if you're unfamiliar with their components

2023-08-29 02:37 UTC, jtabba commented on frontend/src/App.tsx
> +
Why was the router removed?

2023-08-29 02:37 UTC, jtabba commented on frontend/src/components/authentication/Auth0ProviderWithNavigate.tsx
> +export interface WithChildren<T = React.ReactNode> {
Move this to `types.ts`

2023-08-29 02:37 UTC, jtabba commented on frontend/src/components/authentication/Auth0ProviderWithNavigate.tsx
> +    const REDIRECT_URI = process.env.REACT_APP_AUTH0_CALLBACK_URL!;
We can declare these outside of the component scope for better organisation

2023-08-29 02:37 UTC, jtabba commented on frontend/src/components/authentication/Auth0ProviderWithNavigate.tsx
> +}
Install Prettier so your code is automatically formatted on save

2023-08-29 02:37 UTC, jtabba commented on frontend/src/components/authentication/Auth0ProviderWithNavigate.tsx
> +    const onRedirectCallback: (appState?: AppState | undefined, user?: User | undefined) => void = (
Is the void return required here?

2023-08-29 02:37 UTC, jtabba commented on frontend/src/components/authentication/SignInOrOut.tsx
> +				returnTo: '/profile',
Let's redirect to `/home` on sign in

2023-08-29 02:37 UTC, jtabba commented on frontend/src/components/authentication/authenticationGuard.tsx
> +}
Give the interface a more specific name (i.e. `IAuthenticationGuard` or `AuthenticationGuardProps`)

2023-08-29 02:37 UTC, jtabba commented on frontend/src/components/authentication/authenticationGuard.tsx
> +            </div>
Use Chakra

2023-08-29 02:37 UTC, jtabba commented on frontend/src/components/header/NavBar.tsx
> +		<Link to={"/profile"}>Profile</Link>
We'll link `/profile` inside the drop down menu instead. Remove for now

2023-08-29 12:24 UTC, noah-milliken commented on frontend/src/components/authentication/authenticationGuard.tsx
> +            </div>
I used the Chakra Spinner here. Is there a chakra div element as well?

2023-08-29 12:50 UTC, noah-milliken commented on frontend/src/components/authentication/Auth0ProviderWithNavigate.tsx
> +}
OK, I have prettier. But when I run it, it alters all of the files in the Repo.

2023-08-30 02:55 UTC, noah-milliken commented
Prettier updated some formatting, I hope this doesn't Cause any conflicts.

2023-08-30 03:56 UTC, jtabba commented
You need to merge prod into your feature branch before I can approve

2023-08-30 12:47 UTC, noah-milliken commented
That should do it.

2023-09-28 13:51 UTC, jtabba approved these changes

2023-09-28 13:51 UTC, merged