feat: cdw-40 endpoint to store and retrieve users
jtabba/CDW-1 pull request #24
Opened 2023-08-30 15:00 UTC by ifasama

2023-09-03 04:47 UTC, jtabba requested changes
Great work overall Ifa. I've left comments about required changes - if they are confusing let me know and we can set up a call via discord

2023-09-03 04:47 UTC, jtabba commented on backend/src/api/v1/mentorShip/services/types.ts
> +}
What were these included for?

2023-09-03 04:47 UTC, jtabba commented on backend/src/api/v1/mentorShip/services/userServices.ts
We need to fetch a user by their email as it is the only unique identifier we have

2023-09-03 04:47 UTC, jtabba commented on backend/src/api/v1/mentorShip/services/userServices.ts
>          username: args.username
Use email instead

2023-09-03 04:47 UTC, jtabba commented on backend/src/api/v1/mentorShip/services/userServices.ts
> +        AreasOfExpertise: args.AreasOfExpertise,
The A should be lowercase (that's my bad)

2023-09-03 04:47 UTC, jtabba commented on frontend/src/App.tsx
> +import Profile from "./pages/Profile";
Pages are lowercase as we discussed in Discord

2023-09-03 04:47 UTC, jtabba commented on frontend/src/App.tsx
> +			const response = await getSingleUser();
Just for reference we would need to use the users email to retrieve their data

2023-09-03 04:47 UTC, jtabba commented on frontend/src/App.tsx
> +
You've done well with this @ifasama but the front end implementation was not part of this ticket (Noah is currently working on it). This ticket was solely concerned with creating the endpoint. Please remove any front end changes

2023-09-03 04:47 UTC, jtabba commented on frontend/src/requests/getAllUsers.ts
> +}
As above, not part of this ticket. Please remove

2023-09-06 11:44 UTC, ifasama commented
Fix merge conflict after rebase. Needed to forced push but hope it is ok.

2023-09-13 12:10 UTC, jtabba approved these changes

2023-09-13 12:10 UTC, merged