Home text3/cdw42
jtabba/CDW-1 pull request #27
Opened 2023-09-04 13:35 UTC by mrgiles1

After struggling with conflicts for some time, decided to revert to previous commit, rebase, then force push. Hopefully all good.

2023-09-06 09:31 UTC, jtabba requested changes

2023-09-06 09:31 UTC, jtabba commented on frontend/src/components/FeatureSection.tsx
>  }
These stay camelCase, only unchanging variables use uppercase

2023-09-06 09:31 UTC, jtabba commented on frontend/src/pages/home/constants.ts
> +
Small misunderstanding here Danny, only variable names like `subFeaturesProps` or `missionSectionProps` should be using uppercase. Everything else (including interfaces) stays as camelCase

2023-09-06 10:34 UTC, mrgiles1 commented on frontend/src/components/FeatureSection.tsx
>  }
fixed

2023-09-06 10:34 UTC, mrgiles1 commented on frontend/src/pages/home/constants.ts
> +
ok, fixed

2023-09-07 12:00 UTC, jtabba approved these changes

2023-09-07 12:01 UTC, merged